- platform: onvif
  host: 192.168.1.104
  port: 80
  name: onvifcam
  profile: 0
  username:  admin
  
- platform: generic
  name: camera_stream
  still_image_url: "http://192.168.1.104:554/snapshot"
  #stream_source: "rtsp://admin:@192.168.1.15:554/0/av2"
  stream_source: "rtsp://admin:@192.168.1.104:554/0/video1"
  username:  admin
  verify_ssl: false
 
#  - platform: onvif
#    host: 192.168.1.15  
#    port: 80
#    name: onvifcam
#    profile: 1
#    ptz_speed: 0.5
#    pan: 0.5
#    tilt: 0.5
#    zoom: 0.5
    #extra_arguments: -pred 1 -q:v 2
#    
#- platform: ffmpeg
#  input: rtsp://192.168.1.104:554/
#  name: besdercam
#  extra_arguments: -pred 1 -q:v 2
#- platform: generic
#  name: Camera Jardin
#  still_image_url: "http://192.168.1.104/ISAPI/Streaming/channels/101/picture"
#  stream_source: "rtsp://192.168.1.104:554/0/video1"
